### ISSUE TITLE
IllegalArgumentException when using a custom ruleset

### ISSUE THREAD

**Issue by Zero3** [giancosta86/EasyPmd#3] opened 2015-07-14 20:16 UTC
I'm trying to make the new nice feature from #2 work. Unfortunately, EasyPmd throws this at me when I try to use my ruleset file:

```
java.lang.RuntimeException: Couldn't find the class The value of attribute "ref" associated with an element type "null" must not contain the '<' character.
    at net.sourceforge.pmd.RuleSetFactory.classNotFoundProblem(RuleSetFactory.java:270)
    at net.sourceforge.pmd.RuleSetFactory.parseRuleSetNode(RuleSetFactory.java:264)
    at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:176)
    at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:171)
    at net.sourceforge.pmd.RuleSetFactory.createRuleSets(RuleSetFactory.java:135)
    at net.sourceforge.pmd.RuleSetFactory.createRuleSets(RuleSetFactory.java:119)
    at info.gianlucacosta.easypmd.pmdscanner.LinkedPmdScanningStrategy.<init>(LinkedPmdScanningStrategy.java:56)
    at info.gianlucacosta.easypmd.pmdscanner.CacheBasedLinkedPmdScanningStrategy.<init>(CacheBasedLinkedPmdScanningStrategy.java:39)
    at info.gianlucacosta.easypmd.pmdscanner.PmdScanner.<init>(PmdScanner.java:42)
[catch] at info.gianlucacosta.easypmd.ide.IdeScanner.lambda$new$3(IdeScanner.java:97)
    at info.gianlucacosta.easypmd.ide.IdeScanner$$Lambda$25/789461175.onTriggered(Unknown Source)
    at info.gianlucacosta.helios.beans.events.TriggerEvent.fire(TriggerEvent.java:32)
    at info.gianlucacosta.easypmd.ide.options.DefaultOptionsService.setOptions(DefaultOptionsService.java:105)
    at info.gianlucacosta.easypmd.ide.options.EasyPmdOptionsPanelController.applyChanges(EasyPmdOptionsPanelController.java:83)
    at org.netbeans.modules.options.CategoryModel$Category.applyChanges(CategoryModel.java:401)
    at org.netbeans.modules.options.CategoryModel$Category.access$1100(CategoryModel.java:326)
    at org.netbeans.modules.options.CategoryModel.save(CategoryModel.java:222)
    at org.netbeans.modules.options.OptionsPanel.save(OptionsPanel.java:318)
    at org.netbeans.modules.options.OptionsDisplayerImpl$OptionsPanelListener$3.run(OptionsDisplayerImpl.java:520)
    at org.netbeans.modules.progress.ui.RunOffEDTImpl$3.run(RunOffEDTImpl.java:275)
    at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
    at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

For reference, here is the ruleset file I'm trying to load:

```
<?xml version="1.0"?>
<ruleset name="Custom ruleset" xmlns="http://pmd.sourceforge.net/ruleset/2.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 http://pmd.sourceforge.net/ruleset_2_0_0.xsd">
    <description>Zero's PMD ruleset</description>
    <rule ref="rulesets/java/basic.xml"></rule>
    <rule ref="rulesets/java/braces.xml"></rule>
    <rule ref="rulesets/java/codesize.xml"></rule>
    <rule ref="rulesets/java/clone.xml"></rule>
    <rule ref="rulesets/java/controversial.xml"></rule>
    <rule ref="rulesets/java/coupling.xml"></rule>
    <rule ref="rulesets/java/design.xml"></rule>
    <rule ref="rulesets/java/finalizers.xml"></rule>
    <rule ref="rulesets/java/imports.xml"></rule>
    <rule ref="rulesets/java/j2ee.xml"></rule>
    <rule ref="rulesets/java/javabeans.xml"></rule>
    <rule ref="rulesets/java/migrating.xml"></rule>
    <rule ref="rulesets/java/naming.xml"></rule>
    <rule ref="rulesets/java/optimizations.xml"></rule>
    <rule ref="rulesets/java/strictexception.xml"></rule>
    <rule ref="rulesets/java/strings.xml"></rule>
    <rule ref="rulesets/java/sunsecure.xml"></rule>
    <rule ref="rulesets/java/unusedcode.xml"></rule>
    <rule ref="rulesets/java/typeresolution.xml"></rule>
</ruleset>
```

**Comment by Zero3** [comment] 2015-07-14 20:19
Wait. Maybe I loaded the wrong file. Now I get another exception:

    java.lang.RuntimeException: Couldn't find the class The value of attribute "ref" associated with an element type "null" must not contain the '<' character.
        at net.sourceforge.pmd.RuleSetFactory.classNotFoundProblem(RuleSetFactory.java:270)
        at net.sourceforge.pmd.RuleSetFactory.parseRuleSetNode(RuleSetFactory.java:264)
        at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:176)
        at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:171)
        at net.sourceforge.pmd.RuleSetFactory.createRuleSets(RuleSetFactory.java:135)
        at net.sourceforge.pmd.RuleSetFactory.createRuleSets(RuleSetFactory.java:119)
        at info.gianlucacosta.easypmd.pmdscanner.LinkedPmdScanningStrategy.<init>(LinkedPmdScanningStrategy.java:56)
        at info.gianlucacosta.easypmd.pmdscanner.CacheBasedLinkedPmdScanningStrategy.<init>(CacheBasedLinkedPmdScanningStrategy.java:39)
        at info.gianlucacosta.easypmd.pmdscanner.PmdScanner.<init>(PmdScanner.java:42)
    [catch] at info.gianlucacosta.easypmd.ide.IdeScanner.lambda$new$3(IdeScanner.java:97)
        at info.gianlucacosta.easypmd.ide.IdeScanner$$Lambda$25/789461175.onTriggered(Unknown Source)
        at info.gianlucacosta.helios.beans.events.TriggerEvent.fire(TriggerEvent.java:32)
        at info.gianlucacosta.easypmd.ide.options.DefaultOptionsService.setOptions(DefaultOptionsService.java:105)
        at info.gianlucacosta.easypmd.ide.options.EasyPmdOptionsPanelController.applyChanges(EasyPmdOptionsPanelController.java:83)
        at org.netbeans.modules.options.CategoryModel$Category.applyChanges(CategoryModel.java:401)
        at org.netbeans.modules.options.CategoryModel$Category.access$1100(CategoryModel.java:326)
        at org.netbeans.modules.options.CategoryModel.save(CategoryModel.java:222)
        at org.netbeans.modules.options.OptionsPanel.save(OptionsPanel.java:318)
        at org.netbeans.modules.options.OptionsDisplayerImpl$OptionsPanelListener$3.run(OptionsDisplayerImpl.java:520)
        at org.netbeans.modules.progress.ui.RunOffEDTImpl$3.run(RunOffEDTImpl.java:275)
        at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
        at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

**Comment by giancosta86** [comment] 2015-07-16 15:19
Your ruleset is fine - except that the </rule> closing elements could be omitted, in favor of more concise self-closing &lt;rule ref="..." /&gt; tags.
The problem lies in the **controversial.xml** ruleset (which was somehow made into a filter by another plugin?): if you comment out the related line, EasyPmd won't crash.
Furthermore, EasyPmd crashes also if one adds the **Controversial** ruleset via the **Add standard...** button.

**Comment by Zero3** [comment] 2015-07-16 20:32
Wait, didn't you just mention in #1 that you couldn't reproduce the crash? Maybe I misunderstood you!

Anyway, controversial.xml is an official ruleset (http://pmd.sourceforge.net/pmd-4.2.5/rules/controversial.html). What do you mean by "made into a filter by another plugin?". It appears to be distributed with EasyPMD too, because it's in the GUI when you click "Add standard".

I tried commenting out the controversial.xml ruleset, but I get the same exception :(.

**Comment by giancosta86** [comment] 2015-07-16 21:44
Yes, there was a misunderstanding because of the term "Filter" - which, in NetBeans, describes a filter applied to the items in the **Action items** window - exactly the window showing EasyPmd's violations! :) (more precisely, the funnel icon)
I found out that you actually meant "ruleset" while debugging your XML and noticing that **controversial** was indeed a standard ruleset and that it was causing the crash! ^__^
The new version of the plugin is almost ready - stay tuned! :)

**Comment by giancosta86** [comment] 2015-07-17 00:24
EasyPmd 9.0 is ready! ^__^ Thanks for your issue reports! ^__^

https://www.facebook.com/easypmd/posts/390873537776465

**Closed as completed by giancosta86** 2015-07-17 00:24 UTC
Labels: bug

**Comment by Zero3** [comment] 2015-07-19 19:18
Ahaa. My bad for the terminology confusion. I'll give the new version a try!

**Comment by Zero3** [comment] 2015-07-19 19:39
I just tried the new version, and it appears like #1 is fixed :).

Unfortunately, this bug (#3) is still there. When I add the custom ruleset above, I still get the exception above.

**Comment by giancosta86** [comment] 2015-07-21 01:26
Unfortunately, it seems the bug can't be easily reproduced any more... I have tested the plugin with:
- The latest **NetBeans 8.0.2 for Java SE**, on both **Windows** and **Linux**
- **EasyPmd 9**
- A few common plugins, such as the ones for JavaEE and C/C++

No exception was thrown after adding your custom ruleset, and the **Action Items** window was correctly updated...

**Comment by Zero3** [comment] 2015-07-23 13:38
I tested again, and now it works! Hoooray! :+1: 

I believe the cause was a typo in my local copy of the ruleset file I posted above. I was missing a quote,  I think, which apparently triggered the weird exception.

Thanks a lot for your patience and work on fixing this!
